/**
 * Writes src/app/env.ts from the API_BASE environment variable at build time.
 *
 *   API_BASE unset            -> ''            (combined deploy: client served by
 *                                               the API server, same origin)
 *   API_BASE=my-api.host      -> https://my-api.host   (scheme added if missing)
 *   API_BASE=http://localhost:3000 -> used as-is
 *
 * Run before `ng build` for deploys. Local `ng serve` / `ng build` do not run
 * this, so the checked-in localhost default stays put for development.
 */
const fs = require('fs');
const path = require('path');

const raw = (process.env.API_BASE || '').trim();
let apiBase = raw;
if (raw && !/^https?:\/\//.test(raw)) apiBase = `https://${raw}`;
apiBase = apiBase.replace(/\/+$/, '');

const outFile = path.join(__dirname, '..', 'src', 'app', 'env.ts');
const contents = `// Generated by scripts/generate-env.js at build time — edits here are for local dev only.
export const API_BASE = '${apiBase}';
`;

fs.writeFileSync(outFile, contents);
console.log(`generate-env: API_BASE = '${apiBase || "'' (same origin)"}'`);
