// Single place to point the client at the backend. For deploys this file is
// regenerated by scripts/generate-env.js from the API_BASE env var (see
// package.json "build:deploy"); the value below is only used for local dev.
export const API_BASE = 'http://localhost:3000';
